[versions]

activity = "1.8.0"
#noinspection AndroidGradlePluginVersion
agp = "8.7.0"
appcompat = "1.6.1"
colorpicker = "0.0.15"
composeBom = "2023.03.00"
constraintlayout = "2.1.4"
coreKtx = "1.9.0"
espressoCore = "3.5.1"
firebaseBom = "33.4.0"
fragmentTestingManifest = "1.8.4"
gms = "4.4.2"
googlesigninbuttonlibrary = "v2.0.1"
gson = "2.10.1"
kotlin = "2.0.20"
kotlin-serialization = "2.0.20"
kotlinxCoroutinesPlayServices = "1.7.3"
ksp="2.0.20-1.0.24"
ktorBom = "3.0.0"
junit = "4.13.2"
junitVersion = "1.1.5"
lifecycleRuntimeKtx = "2.6.1"
material = "1.10.0"
navigation = "2.8.2"
playServicesAuth = "20.7.0"
room = "2.5.2"
runtimeLivedata = "1.5.1"


[libraries]

androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentTestingManifest" }
androidx-fragment-testing-manifest = { module = "androidx.fragment:fragment-testing-manifest", version.ref = "fragmentTestingManifest" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

colorpicker-v0015 = { module = "com.github.QuadFlask:colorpicker", version.ref = "colorpicker" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }

googlesigninbuttonlibrary = { module = "com.github.joyner-perez:GoogleSignInButtonLibrary", version.ref = "googlesigninbuttonlibrary" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }

ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktorBom" }
ktor-client-android = { module = "io.ktor:ktor-client-android" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization" }
ktor-client-serialization-jvm = { module = "io.ktor:ktor-client-serialization-jvm" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }


[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "gms" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
